### ISSUE TITLE
Strange TS warnings/errors

### ISSUE THREAD

**Issue by adicco** [kitajs/ts-html-plugin#12]
I am encountering the following warning/error with the tsserver LSP:

![image](https://github.com/kitajs/ts-html-plugin/assets/51270459/b2b2d9fa-4239-41a3-bcec-fde50e48bfff)

error is `string | undefined` by the way, not an object.  I would expect the exact opposite behaviour: no xss-prone warning on the "error" variable, but one on the p tag if it didn't have a safe attribute.

Any thoughts? Thank you!

**Comment by adicco** [comment]
A similar one which is also quite odd:

![image](https://github.com/kitajs/ts-html-plugin/assets/51270459/31fea410-8d60-48d9-8e77-adf149b625db)

While in the `EditableListItem` component:

![image](https://github.com/kitajs/ts-html-plugin/assets/51270459/16c9c982-a1d3-401c-916e-2b12e30f41ed)

**Comment by arthurfiorette** [comment]
> error is string | undefined by the way, not an object.

If error may be a string, you must call `Html.escapeHtml` on it, otherwise the error message may contain xss prone characters.

> A similar one which is also quite odd:

The XSS detection tries at it best to determine the expression type. This `<>{(async () => {})()}</>` syntax is pretty odd and you should not write code like that, please hoist this to the top of your function. _(Tech expl: an async function casts the return type to Promise\<R>, which changes the JSX.Element type to only Promise\<string> and the plugin cannot detect it, special cases like `map` calls were done because of its common usage, however I do not have time to implement this specific syntax.)_

> While in the EditableListItem component:

The EditableListItem component itself is xss safe, however the previous example cannot detect that is what will be returned inside the IIFE.

**Comment by adicco** [comment]
Thanks @arthurfiorette, I will try these various pointers. And good to know re: the type being cast to a string instead of the JSX.Element
